/obj/item/clothing/topic_examine(mob/user)
	. = ..()
	if(LAZYLEN(armor_list))
		armor_list.Cut()
	if(subarmor.edge_protection)
		armor_list += list("EDGE PROTECTION" = subarmor.edge_protection)
	if(subarmor.crushing)
		armor_list += list("BLUNT" = subarmor.crushing)
	if(subarmor.cutting)
		armor_list += list("SLASHING" = subarmor.cutting)
	if(subarmor.piercing)
		armor_list += list("PIERCING" = subarmor.piercing)
	if(subarmor.impaling)
		armor_list += list("IMPALING" = subarmor.impaling)
	if(subarmor.laser)
		armor_list += list("LASER" = subarmor.laser)
	if(armor.bomb)
		armor_list += list("EXPLOSIVE" = armor.bomb)
	if(armor.energy)
		armor_list += list("ENERGY" = armor.energy)
	if(armor.bio)
		armor_list += list("BIOLOGICAL" = armor.bio)

	if(LAZYLEN(durability_list))
		durability_list.Cut()
	if(armor.fire)
		durability_list += list("FIRE" = armor.fire)
	if(armor.acid)
		durability_list += list("ACID" = armor.acid)

	if(LAZYLEN(body_parts_list))
		body_parts_list.Cut()
	body_parts_list = body_parts_covered2organ_names(initial(body_parts_covered))
	for(var/covered_zone in body_parts_list)
		body_parts_list -= covered_zone
		body_parts_list += capitalize_like_old_man(parse_zone(covered_zone))

	if(LAZYLEN(armor_list) || LAZYLEN(durability_list))
		. += span_boldnotice("<a href='?src=[REF(src)];armor=1'>Defense</a>")
	if(LAZYLEN(body_parts_list))
		. += span_boldnotice("<a href='?src=[REF(src)];coverage=1'>Coverage</a>")
