#define CARDIAC_ARREST_SLOWDOWN 5
#define SHOCK_STAGE_SLOWDOWN 0.25
#define TRAUMATIC_SHOCK_SLOWDOWN_MULTIPLIER 0.03
#define LIMB_EFFICIENCY_MIN_SLOWDOWN -6
#define LIMB_EFFICIENCY_MAX_SLOWDOWN 6
#define SPEEDBOOST_SPEED_INCREASE 0.1

#define SPRINT_DEFAULT_SPEED_INCREASE 1
#define SPRINT_DEFAULT_STAMINA_COST 2
#define SPRINT_DEFAULT_FATIGUE_COST 4
#define SPRINT_MAX_STAMLOSS 50
#define SPRINT_MAX_FATIGUELOSS 50
