/mob/living/carbon/human/death(gibbed)
	. = ..()
	if(!QDELETED(src))
		update_hud_breath()
	if(stat >= DEAD)
		if(reagents?.has_reagent(/datum/reagent/consumable/shit, 1))
			client?.give_award(/datum/award/achievement/misc/eatshitanddie, src)

/mob/living/carbon/human/revive(full_heal, admin_revive, excess_healing)
	. = ..()
	if(.)
		if(dna?.species)
			dna.species.spec_revival(src)
	update_hud_breath()
	if(stat < DEAD)
		remove_verb(src, /mob/living/carbon/human/proc/prepare_to_walk)
