GLOBAL_LIST_INIT(whoopsie, world.file2list('modular_septic/strings/whoopsie.txt'))
GLOBAL_LIST_INIT(xbox_rage, world.file2list('modular_septic/strings/xbox.txt'))
GLOBAL_LIST_INIT(eww, world.file2list('modular_septic/strings/ew.txt'))
GLOBAL_LIST_INIT(godforsaken_success, world.file2list('modular_septic/strings/xbox.txt'))
GLOBAL_LIST_INIT(godforsaken_failure, world.file2list('modular_septic/strings/ew.txt'))
